### ISSUE TITLE
Not sure how to get profile working

### ISSUE THREAD

**Issue by sirmaestro** [JAB-dev/mpv-frame-interpolation#1]
Hey, cool project here. I want to get it working but I'm not too familiar with mpv configs and profiles. I don't know how to change or use the profile in mpv. Right click just pauses the video for me.
I've put the files here as you've stated in the guide
`C:\Users\USERNAME\AppData\Roaming\mpv\mpv.conf`
```
#Frame interpolation
[FrameInterpolation]
vf=vapoursynth="C:\Users\USERNAME\AppData\Roaming\mpv\FrameInterpolation.vpy"
profile-restore = copy
```
`C:\Users\USERNAME\AppData\Roaming\mpv\input.conf`
```
_ set profile FrameInterpolation #menu: Profiles > profile FrameInterpolation
```
`C:\Users\USERNAME\AppData\Roaming\mpv\FrameInterpolation.vpy`

I'm using mpv Windows builds by shinchiro version 0.35.0

**Comment by JAB-dev** [comment]
Hello, At the moment the guide is specifically for mpv.net for the profile menu to work correctly

It also changes the path you need C:\Users\USERNAME\AppData\Roaming\mpv.net 

https://github.com/mpvnet-player/mpv.net

in the future I will probably do something that works on all builds

**Comment by sirmaestro** [comment]
Ah sweet thank you, I got it working now. It looks pretty good when it's working!
Although sometimes the video goes faster than the audio and it's out of sync, do you know how to fix this?

**Comment by JAB-dev** [comment]
I think it goes out of sync sometimes because of the performance hit. Easiest fix is just to arrow key back <- and let mpv.net resync
